https://www.youtube.com/watch?v=EYnC4ACIt2g&list=PLqcF-HKeIFjPY_gJDbqoouJEbGNnYhboT&index=1

In [7]:
#this program predicts stock prices by using machine learning models

In [8]:
#install dependencies 

In [9]:
!pip install quandl

In [10]:
import quandl
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [11]:
#get the stock data
df = quandl.get("WIKI/FB")

In [12]:
print(df.head())

             Open   High    Low    Close       Volume  Ex-Dividend  \
Date                                                                 
2012-05-18  42.05  45.00  38.00  38.2318  573576400.0          0.0   
2012-05-21  36.53  36.66  33.00  34.0300  168192700.0          0.0   
2012-05-22  32.61  33.59  30.94  31.0000  101786600.0          0.0   
2012-05-23  31.37  32.50  31.36  32.0000   73600000.0          0.0   
2012-05-24  32.95  33.21  31.77  33.0300   50237200.0          0.0   

            Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  \
Date                                                                  
2012-05-18          1.0      42.05      45.00     38.00     38.2318   
2012-05-21          1.0      36.53      36.66     33.00     34.0300   
2012-05-22          1.0      32.61      33.59     30.94     31.0000   
2012-05-23          1.0      31.37      32.50     31.36     32.0000   
2012-05-24          1.0      32.95      33.21     31.77     33.0300   

           

In [13]:
#Getthe adjusted close price
df = df[['Adj. Close']]

In [14]:
print(df.head())

            Adj. Close
Date                  
2012-05-18     38.2318
2012-05-21     34.0300
2012-05-22     31.0000
2012-05-23     32.0000
2012-05-24     33.0300


In [41]:
#A variable to predict 'n' days out into the future
forecast_out = 30
#Create another variable in the column (the target or dependable ),shifted n units up!
df['Prediction']= df[['Adj. Close']].shift(-forecast_out)

In [16]:
print(df.head()) #moving the prices up by one unit.if todays prices is 38 it is predicted tomorrows price will be 34 etc

            Adj. Close  Prediction
Date                              
2012-05-18     38.2318      30.771
2012-05-21     34.0300      31.200
2012-05-22     31.0000      31.470
2012-05-23     32.0000      31.730
2012-05-24     33.0300      32.170


In [17]:
print(df.tail())

            Adj. Close  Prediction
Date                              
2018-03-21      169.39         NaN
2018-03-22      164.89         NaN
2018-03-23      159.39         NaN
2018-03-26      160.06         NaN
2018-03-27      152.19         NaN


In [18]:
# Check the columns of the DataFrame
print(df.columns)

# Ensure the 'Prediction' column exists


Index(['Adj. Close', 'Prediction'], dtype='object')


In [19]:
# Convert dataframe into Numpy array
X = np.array(df.drop(['Prediction'], axis=1))

# Remove last N rows
X = X[:-forecast_out]
X

array([[ 38.2318],
       [ 34.03  ],
       [ 31.    ],
       ...,
       [171.5499],
       [175.98  ],
       [176.41  ]])

In [20]:
### Create the dependent dataset Y ###
### convert all the y values into numpy arrays including the NaN values.
y = np.array(df['Prediction'])

# Get all of the Y values except the last N rows
y = y[:-forecast_out]
y



array([ 30.771,  31.2  ,  31.47 , ..., 159.39 , 160.06 , 152.19 ])

In [21]:
## Split the data into 80% traning and 20% testing
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2)

In [23]:
#create and train the model using Support Vector Machine Learning model.
svr_rbf =SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_rbf.fit(X_train,y_train)

SVR(C=1000.0, gamma=0.1)

In [27]:
#TESTING MODEL :SCORE RETURNS THE COEFFICIENT OF DETERMINATION R^2 OF THE PREDICTION
svm_confidence = svr_rbf.score(X_test,y_test)
print("The svm_confidence score is:",svm_confidence)

The svm_confidence score is: 0.9851325175930897


In [28]:
#create and train the linear regression model
clrm = LinearRegression()
clrm.fit(X_train , y_train)

LinearRegression()

In [29]:
#TESTING MODEL :SCORE RETURNS THE COEFFICIENT OF DETERMINATION R^2 OF THE PREDICTION
#BEST SCORE IS A SCORE OF 1
clrm_confidence = clrm.score(X_test,y_test)
print("The clrm_confidence score is:",clrm_confidence)

The clrm_confidence score is: 0.9804591908131837


In [48]:
#Set x_forecast equal to the last 30 rows of the adjusted close price in the original 
df
x_forecast = np.array(df.drop(['Prediction'],1))[-forecast_out:]
x_forecast


C:\Users\tanis\AppData\Local\Temp\ipykernel_18500\2762601020.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x_forecast = np.array(df.drop(['Prediction'],1))[-forecast_out:]


array([[173.15],
       [179.52],
       [179.96],
       [177.36],
       [176.01],
       [177.91],
       [178.99],
       [183.29],
       [184.93],
       [181.46],
       [178.32],
       [175.94],
       [176.62],
       [180.4 ],
       [179.78],
       [183.71],
       [182.34],
       [185.23],
       [184.76],
       [181.88],
       [184.19],
       [183.86],
       [185.09],
       [172.56],
       [168.15],
       [169.39],
       [164.89],
       [159.39],
       [160.06],
       [152.19]])

In [51]:
#Linear model prediction:
clrm_prediction = clrm.predict(x_forecast)

In [50]:
print(clrm_prediction)

[177.11569728 183.55495033 183.9997339  181.37146735 180.00679049
 181.92744681 183.0191883  187.36593683 189.02376649 185.51604152
 182.34190423 179.93602946 180.62342225 184.44451747 183.81777698
 187.79050296 186.40560866 189.32702802 188.8519183  185.94060766
 188.2757214  187.94213372 189.18550597 176.51928295 172.06133853
 173.3148195  168.76589663 163.206102   163.88338608 155.9278254 ]


In [52]:
svm_prediction = svr_rbf.predict(x_forecast)

In [53]:
print(svm_prediction)

[177.05157605 178.83179966 178.53818742 177.38946419 176.9998477
 177.8311302  178.92515673 187.06405471 179.14358128 181.88197534
 178.33404026 176.93401073 177.26924399 178.51295842 178.65523244
 185.09508247 186.66894972 178.9093843  179.55984417 184.31670514
 182.21713809 184.2141307  178.93971557 178.34531184 171.69847266
 172.21736357 172.18432145 168.03225907 166.14545708 157.83496617]
